characters = [
   ""
   "Bayonetta",
   "Hero",
   "Banjo & Kazooie",
   "Captain Falcon",
   "Chrom",
   "Cloud",
   "Daisy",
   "King Dedede",
   "Kazuya",
   "Diddy Kong",
   "Terry",
   "Donkey Kong",
   "Duck Hunt",
   "Sephiroth",
   "Pyra / Mythra",
   "Falco",
   "Fox",
   "Ivysaur",
   "Mr. Game & Watch",
   "Ganondorf",
   "Incineroar",
   "Greninja",
   "Ike",
   "Inkling",
   "Joker",
   "Corrin",
   "Ken",
   "Kirby",
   "Bowser",
   "Giga Bowser",
   "Bowser Jr.",
   "King K. Rool",
   "Link",
   "Little Mac",
   "Charizard",
   "Lucario",
   "Lucas",
   "Lucina",
   "Luigi",
   "Mario",
   "Dr. Mario",
   "Marth",
   "Byleth",
   "Meta Knight",
   "Mewtwo",
   "Mii Brawler",
   "Mii Gunner",
   "Mii Swordfighter",
   "Mii Brawler",
   "Mii Gunner",
   "Mii Swordfighter",
   "Villager",
   "Ice Climbers",
   "Ness",
   "Piranha Plant",
   "Pac-Man",
   "Palutena",
   "Peach",
   "Ivysaur",
   "Pichu",
   "Steve",
   "Pikachu",
   "Olimar",
   "Pit",
   "Dark Pit",
   "Charizard",
   "Ice Climbers",
   "Jigglypuff",
   "Squirtle",
   "Robin",
   "Richter",
   "Ridley",
   "R.O.B.",
   "Mega Man",
   "Rosalina & Luma",
   "Roy",
   "Ryu",
   "Samus",
   "Dark Samus",
   "Sheik",
   "Isabelle",
   "Shulk",
   "Simon",
   "Snake",
   "Sonic",
   "Zero Suit Samus",
   "Min Min",
   "Toon Link",
   "Sora",
   "Wario",
   "Wii Fit Trainer",
   "Wolf",
   "Yoshi",
   "Young Link",
   "Zelda",
   "Squirtle"
]

stages = [
  "3D Land",
  "75m",
  "Arena Ferox",
  "Balloon Fight",
  "Battlefield",
  "Big Battlefield",
  "Big Blue",
  "Boxing Ring",
  "Bridge of Eldin",
  "Brinstar",
  "Brinstar Depths",
  "Castle Siege",
  "Coliseum",
  "Corneria",
  "Delfino Plaza",
  "Distant Planet",
  "Dracula's Castle",
  "Dream Land",
  "Dream Land GB",
  "Duck Hunt",
  "Figure-8 Circuit",
  "Final Destination",
  "Find Mii",
  "Flat Zone X",
  "Fountain of Dreams",
  "Fourside",
  "Frigate Orpheon",
  "Gamer",
  "Garden of Hope",
  "Gaur Plain",
  "Gerudo Valley",
  "Golden Plains",
  "Great Bay",
  "The Great Cave Offensive",
  "Great Plateau Tower",
  "Green Greens",
  "Green Hill Zone",
  "Halberd",
  "Hanenbow",
  "Hyrule Castle",
  "Jungle Japes",
  "Kalos Pokemon League",
  "Kongo Falls",
  "Kongo Jungle",
  "Living Room",
  "Luigi's Mansion",
  "Lylat Cruise",
  "Magicant",
  "Mario Bros.",
  "Mario Circuit",
  "Mario Galaxy",
  "Midgar",
  "Moray Towers",
  "Mushroom Kingdom",
  "Mushroom Kingdom II",
  "Mushroomy Kingdom",
  "Mushroom Kingdom U",
  "Mute City SNES",
  "New Donk City Hall",
  "New Pork City",
  "Norfair",
  "Onett",
  "Pac-Land",
  "Palutena's Temple",
  "Paper Mario",
  "Peach's Castle",
  "Princess Peach's Castle",
  "PictoChat 2",
  "Pilotwings",
  "Pirate Ship",
  "Pokemon Stadium",
  "Pokemon Stadium 2",
  "Port Town Aero Dive",
  "Prism Tower",
  "Rainbow Cruise",
  "Reset Bomb Forest",
  "Saffron City",
  "Shadow Moses Island",
  "Skyloft",
  "Skyworld",
  "Smashville",
  "Spear Pillar",
  "Spirit Train",
  "Summit",
  "Super Happy Tree",
  "Super Mario Maker",
  "Suzaku Castle",
  "Temple",
  "Tomodachi Life",
  "Tortimer Island",
  "Town and City",
  "Umbra Clock Tower",
  "Unova Pokemon League",
  "Venom",
  "WarioWare, Inc.",
  "Wii Fit Studio",
  "Windy Hill Zone",
  "Wrecking Crew",
  "Wuhu Island",
  "Yoshi's Island",
  "Yoshi's Story",
  "Wily's Castle",
  "Small Battlefield",
  "Northern Cave",
  "Hollow Bastion",
  ""
]